runtime: nodejs14  # Node Version

env_variables:
  # Variable used to set the environment to production
  NODE_ENV: "production"
  PORT: 8080  # Port that the app will listen to

# automatic_scaling:
#   # Configuration for Google App Engine automatic scaling
#   target_cpu_utilization: 0.65
#   min_instances: 1
#   max_instances: 10

# This is needed to run the app on Google App Engine
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
